### ISSUE TITLE
Use default import path in crossbuild or abort

### ISSUE THREAD

**Issue by grobie** [prometheus/promu#10]
The detected repo path in `promu info` is correct. It's not used in crossbuild though.

`docker run --rm -t -v $PWD:/app prom/golang-builder:1.5.3-main -i  -p 'linux/amd64 ...`

Instead of passing in an empty variable, promu should at least abort with something like `unknown repo URL`, but even better use the default provided by `repoLocation()`.

**Comment by sdurrheimer** [comment]
The thing about setting `repoLocation()` as default value for `repository.path` is that it won't work with forks.

**Comment by sdurrheimer** [comment]
One way to find the correct import path would be to use Go 1.4 annotation to identify the [canonical import path](https://golang.org/doc/go1.4#canonicalimports).

Therefore, by having this  comment in your code:
```
package main // import "github.com/prometheus/node_exporter"
```

It will let us do: `go list -e -f '{{.ImportComment}}' ` to recover the correct project import path.

**Comment by grobie** [comment]
That looks like a great idea.

What is the use case of the current `repoLocation()` function then? It seems `prom build` uses it currently, but this will equally fail if someone forks a project and tries to run `promu build`, no?

**Comment by sdurrheimer** [comment]
`promu build` doesn't use `repoLocation()` directly. It uses the `ProjectInfo` struct which is partially initiated by the `repoLocation()` func (https://github.com/prometheus/promu/blob/master/cmd/info.go#L50). So `repoLocation()` is the source of information for `Owner`, `Name` and `Repo` properties.

Currently `promu build` only uses `Version` and `Name` of that struct.

However, `Owner` and `Name` are used by the `promu release` command (https://github.com/prometheus/promu/blob/master/cmd/release.go#L66), which is correct when using a fork.

**Comment by sdurrheimer** [comment]
I just realized, the canonical import path annotation will not work great for `prometheus/prometheus` because of multiple binaries.

**Comment by grobie** [comment]
Alright, then let's make it a requirement to set in .promu.yml.
