### ISSUE TITLE
Unconditional fully static linking on Linux causes problem

### ISSUE THREAD

**Issue by fweimer** [prometheus/promu#102]
“promu build” unconditionally passes `-extldflags -static` to the Go build tools, instructing the external linker to produce fully static binaries.  However, some projects built with “promu build” require a working `getaddrinfo` function, so they cannot use fully static linking:

* [Panic and crash when supervisord collector enabled, yet supervisord not listening on 127.0.0.1:9001](https://github.com/prometheus/node_exporter/issues/1007)
* [getaddrinfo causes segfault if multithreaded and linked statically](https://sourceware.org/bugzilla/show_bug.cgi?id=10652)

The Go toolchain will automatically switch between static and dynamic linking, to meet the project's requirements, so it would be preferably not to override this decision.

**Comment by matthiasr** [comment]
Are the binaries always run with a consistent libc?

**Comment by fweimer** [comment]
The upstream bug I referred to happens with matching binaries.  Static linking, threads, and `dlopen` (whether explicit or implicit as part of `getaddrinfo` etc.) are extremely buggy at the moment.

**Comment by matthiasr** [comment]
What I meant to ask was – given the usage of the binaries we provide, can we even build them as dynamic binaries?

**Comment by pytimer** [comment]
Hi, is there any progress? I also have this problem. 

I change code to comment `-extldflags -static`, and build again, it works well.

**Comment by pytimer** [comment]
@simonpasquier  Thanks for your reply.

This PR not merge currently, if i want to use, do i need to make this changes in my fork repos? Can not directly use the officially release.
