### ISSUE TITLE
Remove cobra/viper dependency

### ISSUE THREAD

**Issue by SuperQ** [prometheus/promu#109]
This project seems to be one of the only projects within Prometheus that uses cobra/viper for configuration.  In order to standardize things, and possibly reduce @TheTincho workload, I think it would be better to follow the standard use of kingpin.v2 and yaml.v2.

See: https://github.com/prometheus/promu/pull/91

**Comment by SuperQ** [comment]
@pgier I think this is done now. :grin:

**Comment by pgier** [comment]
@SuperQ yep, I think this can be closed.
