### ISSUE TITLE
v0.3.0 removes tarball prefix flag

### ISSUE THREAD

**Issue by carlpett** [prometheus/promu#132]
There is no notice the changelog of 0.3.0 having a breaking change in the form of removing `--prefix`, which was done in #126. It is also not noted in the PR itself.

Was there a reason to remove it? If so, it should be noted in the changelog, otherwise would a PR to reinstate it be accepted?

@simonpasquier @SuperQ

**Comment by simonpasquier** [comment]
> Was there a reason to remove it?

I can't find a good reason why I committed this unrelated change... I'll send a PR to fix it. Thanks for reporting!

**Comment by carlpett** [comment]
Thanks!
