### ISSUE TITLE
Improve error handling, be explicit about special CHANGEOG format required.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/promu#160]
This is too vague: https://circleci.com/gh/prometheus/prometheus/14599 

Problematic piece of code: https://github.com/prometheus/promu/blob/533bdce9a5236fdabed601233b5bc48c90f020cb/cmd/release.go#L110
Also expecting certain CHANGELOG format was surprising for release shepherd. I am pretty sure we can do better. Happy to help in my free time as well.

**Comment by juliusv** [comment]
In my case I forgot to add the date to the changelog entry, but promu expects a space after the version (which wasn't there because no date followed): https://github.com/prometheus/promu/blob/da3ea9df6d18266bf5ba1759824637f6b9228fbf/cmd/release.go#L247
