### ISSUE TITLE
Provide sha256 checksums for all tarballs

### ISSUE THREAD

**Issue by grobie** [prometheus/promu#18]
In order to be provide additional means to verify the integrity of a downloaded tarball, let's provide checksums.

It's fine to create a single file with checksum for all binaries. Line based is fine, or JSON. We can then use these files to build a downloads page.

**Comment by lhirlimann** [comment]
So what part of the code should I poke at in order to add this ? https://github.com/prometheus/docs/blob/master/lib/helpers/download.rb isn't good, I probably need to tackle build stuff can someone link where these are ?

**Comment by grobie** [comment]
Before we start discussing the implementation details, I'd like to hear the actual use cases for checksum people have. Then we can decide whether our implementation idea is sufficiently secure for that.

Whatever we come up with, we have to clearly document what kind of guarantee we can provide around our binaries+checksums and what attack vectors will remain open.

**Comment by lhirlimann** [comment]
So th emain reason I'd like checksum/+signature is the ability to package/repackage bthe product for my favorite distros. Most packages manager pakers know how to check either cheksum/signature.
Having the product in main distros would boost it's usage.
