### ISSUE TITLE
crossbuild platform flag only accepts two platforms

### ISSUE THREAD

**Issue by clnperez** [prometheus/promu#184]
Hopefully I'm not just misusing the flags...

```
promu crossbuild --platforms=linux/ppc64le linux/s390x linux/amd64 -v
promu: error: unexpected linux/amd64, try --help
```

```
promu crossbuild -v --platforms=linux/ppc64le linux/s390x linux/amd64
promu: error: unexpected linux/amd64, try --help
```

```
promu crossbuild -v --platforms=linux/ppc64le darwin/amd64 linux/s390x
promu: error: unexpected linux/s390x, try --help
```

```
promu crossbuild --platforms=linux/ppc64le darwin/amd64 linux/s390x linux/s390x
promu: error: unexpected linux/s390x, try --help
```

It complains about whatever you put in the last spot.

os: fedora 32
arch: x86_64
docker version: 19.03.11
go version: go version go1.13.9 linux/amd64

promu downloaded from https://github.com/prometheus/promu/releases. Both v0.4 and v0.5 fail the same way.

**Comment by grobie** [comment]
The flag description is very confusing here. In order to specify multiple platforms, the flag name needs to be repeated.

```
promu crossbuild --platforms=linux/ppc64le --platforms=linux/s390x --platforms=linux/amd64
```

**Comment by clnperez** [comment]
ooooo. Yes that help-text and the name of the flag are both misleading. I'd considered a quick PR to update the help-text  -- but then leaving it named `platforms` plural seems wrong. So it seems that this should be modified to take a space-separated list, or the flag name shouldn't be plural. :D

**Comment by SuperQ** [comment]
I've updated the help text to make this more clear.

https://github.com/prometheus/promu/pull/204
