### ISSUE TITLE
would like cross built promu binaries for GOOS=illumos GOARCH=amd64

### ISSUE THREAD

**Issue by jclulow** [prometheus/promu#191]
The Prometheus build attempts to download a prebuilt `promu` binary from GitHub.  The software builds and works on illumos/amd64 systems today, but obviously is not currently being built as part of the official CI/CD pipeline or published in the releases.

Can we get illumos binaries added to the releases please?  I am happy to be a point of contact in future if any build issues arise.  If I should file a PR, I'd appreciate it if you could point me in the right direction so I can make the right change!

Thanks!

**Comment by roidelapluie** [comment]
I have no issue with that except that the .promu.yml builds for the default arch: https://github.com/prometheus/promu/blob/master/.promu.yml

Adding illumos to the default arch might be a bit too much, and adding the default archs+illumos would be flaky.

cc @SuperQ

**Comment by SuperQ** [comment]
I think we can add single OS/arch combos to the default build.

**Comment by roidelapluie** [comment]
@jclulow can you open a pull request to https://github.com/prometheus/promu/blob/master/cmd/crossbuild.go adding illumos?

Note that it does not mean that we will publish prometheus/prometheus, which would require more team members acknowledging the idea.
