### ISSUE TITLE
darwin/arm64 (Apple Silicon M1) support

### ISSUE THREAD

**Issue by jamesrwhite** [prometheus/promu#199]
Hi,

I wanted to ask if there any plans to build binaries for `darwin/arm64` to support running `node_exporter` natively on MacOS machines running M1 processors?

This would require updating to Go 1.16 also I believe as that's when support for that arch was added.

We currently have the following version of `node_exporter` running:
```
node_exporter, version 1.1.1 (branch: , revision: )
  build user:       Homebrew
  build date:
  go version:       go1.15.7
  platform:         darwin/amd64
```

We are running it under [Rosetta](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment) on MacOS 11.0.1 but there are known issues with earlier versions of Rosetta and Go (https://github.com/golang/go/issues/42700) that I believe we are also seeing. Supposedly they are fixed in later versions of Rosetta but I'd prefer if we could run it natively regardless.

I'm not that familiar with the code base but I'm happy to help with implementing/testing if I can. I had a quick look and can see there's various files where 1.15 is mentioned and the darwin builds seem to be in `.promu-cgo.yml`.

Thanks

**Comment by jamesrwhite** [comment]
@SuperQ Thanks for looking at this. What's left to add support to `node_exporter` itself?

I had a go at this myself [here](https://github.com/prometheus/node_exporter/compare/master...jamesrwhite:darwin-arm64?expand=1) but I wanted to check if there was anything else required? I'm happy to make the required changes and open a PR. 

We're currently running a `darwin/arm64` binary [from homebrew](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/node_exporter.rb) that runs fine with the exception of the `filesystem` collector not being available.

**Comment by SuperQ** [comment]
I think I finally got the golang-builder working correctly for CGO crossbuilds of the node_exporter.

https://github.com/prometheus/node_exporter/pull/2020

**Comment by jamesrwhite** [comment]
@SuperQ Just seen the updates to your PR, thanks again for looking at this 👍 

I still think some changes [like these](https://github.com/jamesrwhite/node_exporter/commit/c2fa9fd775f7879871537d780409314a40776c21) will be needed to get the `filesystem` collector working, could you add those in or would you prefer I open a separate PR?

**Comment by SuperQ** [comment]
Yes, you're right, we need to modify the build flag. Rather than enumerate it, we can change `darwin,amd64` to just `darwin`.

Feel free to open a PR.

**Comment by SuperQ** [comment]
Actually, I can just add that to the existing PR.
