### ISSUE TITLE
Is there a way to compile binary files with multiple architectures?

### ISSUE THREAD

**Issue by dartagnanli** [prometheus/promu#290]
Is there a way to compile binary files with multiple architectures，like GOOS=linux GOARCH=amd64 go build ...? I haven't found a way to use it?

**Comment by itsNotMyUsername** [comment]
There is, simply run 
`promu crossbuild -v` to run all platforms in your config or selected ones `promu crossbuild -v -p linux/amd64 -p linux/arm64 -p linux/ppc64le`

**Comment by dartagnanli** [comment]
> There is, simply run `promu crossbuild -v` to build all platforms in your config or selected ones `promu crossbuild -v -p linux/amd64 -p linux/arm64 -p linux/ppc64le`

oh,but I find this is building an image not a binary file...

**Comment by dartagnanli** [comment]
> There is, simply run `promu crossbuild -v` to build all platforms in your config or selected ones `promu crossbuild -v -p linux/amd64 -p linux/arm64 -p linux/ppc64le`

Got it,Thank you very much.
