### ISSUE TITLE
Use new version format in release names

### ISSUE THREAD

**Issue by grobie** [prometheus/promu#33]
The version format has been changed to include a `v` prefix. Should we include this in directory and tarball names for consistency?

@fabxc @sdurrheimer

**Comment by sdurrheimer** [comment]
I'm fine with both, with or without the `v`. We just need to keep in mind this change might hurt peoples automation scripts :).

**Comment by grobie** [comment]
The applied rename already hurt ours. We have VERSION variables in all our
makefiles, we now need to append a v depending on the context.

**Comment by beorn7** [comment]
I don't think we need it in the tarball. It is natural to have the version number in the form we have. Tags, however, can be anything, not just versions. That's the rationale of having the `v` prefix, essentially namespacing. That doesn't apply to the directory and tarball name.
