### ISSUE TITLE
Fetch `github-release` dependency if necessary when using `promu release`

### ISSUE THREAD

**Issue by sdurrheimer** [prometheus/promu#4]

**Comment by grobie** [comment]
Isn't it possible to use it as library and include directly in promu?

**Comment by sdurrheimer** [comment]
I don't think this is possible with `aktau/github-release`.

**Comment by sdurrheimer** [comment]
We should maybe consider using a existing library like https://github.com/google/go-github, or maybe write our own with the bare minimum.
