### ISSUE TITLE
promu build does not work on Windows

### ISSUE THREAD

**Issue by carlpett** [prometheus/promu#44]
I'm trying to use promu for [wmi_exporter](https://github.com/martinlindhe/wmi_exporter) and ran into some issues on Windows. I have some fixes coming in a pull request, but here is a list of the things I've noticed so far:

- The user part of the build info is mangled in ldflags, this is what it looks like on my machine `-X github.com /m@MY-HOST`
- The `go-shell` package does not report panics in any way, but instead simply swallows any errors. Unsure if this is a bug in the package or the use of it (`defer shell.ErrExit()`)
- The default shell is `/bin/sh`, which does not exist on Windows, and causes a panic (which as mentioned is swallowed, and promu exits with status code 0)

Is Windows compatibility a goal of promu? I have a patch which fixes the first item, but from some experimentation with go-shell, it seems a bit hard to make it work on Windows. Will try some more, but if it is a non-goal for this project, I'll just have to use something else.

**Comment by carlpett** [comment]
Go-shell does some management of argument quoting internally it seems, after which Go (on Windows only) applies some rules of its own (https://github.com/golang/go/blob/master/src/syscall/exec_windows.go#L17). The effect is that the ldflags parameter has its quotes escaped, which turns the call into `go build [...] -ldflags "\"-s" -X[...]`. Might be possible to work around, somehow

**Comment by sdurrheimer** [comment]
To be honest, I never really thought about Windows when I was doing `promu`, so I'm not surprised we got some issues here.

I would totally merge Windows compatibility PRs, if we are able to make it work.

I will also take a look on my side to see if I can improve those things.

**Comment by carlpett** [comment]
@sdurrheimer Cool! I think the main culprit is `go-shell`, really. I'll give fixing it a try (probably just providing another code path if running on Windows).
