### ISSUE TITLE
Produce zip files for windows binaries

### ISSUE THREAD

**Issue by gambrose** [prometheus/promu#46]
It would be simpler for windows users to have zip archives to unpack.
There is build in support for zip files on windows. You have to download an application to unpack a tarball.

**Comment by NicolaiPetri** [comment]
I think this would be a quite trivial task - but I'm totally noob to go so I hope someone else might step in :) Else someone could maybe write a quick overview of how to approach fixing this ?

**Comment by grobie** [comment]
It's trivial in principle, but not in practice unfortunately. The code base doesn't make it a straight forward change due to explicit coupling to `tarball` naming and quite unidiomatic go code. We'll need some more refactorings before we can proceed here.

**Comment by oblalex** [comment]
+1 for this. Even when it's possible to use 3rd-party tools for unpacking tarballs, it's a bit of pain during automation. And it's an extra dependency to install just a single service.
