### ISSUE TITLE
crossbuild attempts to compile unsupported openbsd-armv5

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/promu#65]
Crossbuild for master in alertmanager is failing on openbsd-armv5:

```
# openbsd-armv5

>> building binaries

 >   alertmanager

 >   amtool

# github.com/prometheus/alertmanager/vendor/golang.org/x/sys/unix

/go/src/github.com/prometheus/alertmanager/vendor/golang.org/x/sys/unix/flock.go:18: undefined: Flock_t

/go/src/github.com/prometheus/alertmanager/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:36: undefined: Cmsghdr

/go/src/github.com/prometheus/alertmanager/vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42: undefined: Cmsghdr
```
https://circleci.com/gh/prometheus/alertmanager/619

Looking at package `x/sys/unix`, the files the expected file for these definitions `x/sys/unix/ztypes_openbsd_arm.go` does not exist.

Checking against the site for supported platforms, they only have armv7:
https://www.openbsd.org/plat.html

Seems like this should be removed from the crossbuild?

**Comment by stuartnelson3** [comment]
cf. https://github.com/prometheus/alertmanager/issues/723

**Comment by grobie** [comment]
Sounds good to me. I actually don't understand how we translate arm to arm5/arm6/arm7.

**Comment by sdurrheimer** [comment]
@grobie Nothing special, a hard-coded in the [golang-builder / arm image](https://github.com/prometheus/golang-builder/blob/master/1.8/arm/rootfs/builder.sh#L27).

**Comment by grobie** [comment]
@sdurrheimer So that means we can't easily just disable openbsd support vor ARMv5, but leave Linux support for ARMv5, right? Any suggestion how to handle this?

**Comment by sdurrheimer** [comment]
Need to rethink a little bit the system. I wasn't aware of such incompatibilities. I didn't play much with ARM.

**Comment by grobie** [comment]
Alternatively, maybe we can just disable all ARMv5 builds. @discordianfish Do you know whether ARMv5 is still widely in use?

**Comment by discordianfish** [comment]
It is, at least RPI 1+2 are armv5

**Comment by sdurrheimer** [comment]
Looking at [this page](https://github.com/golang/go/wiki/GoArm#supported-operating-systems)
we should only support:
- linux: v5, v6, v7
- freebsd: v6, v7
- openbsd: v7
- netbsd: v6, v7

Am I right ?

**Comment by stuartnelson3** [comment]
That seems correct. As things change we can always update support, too.

**Comment by grobie** [comment]
Cool, so we can just replicate that matrix in the golang builder and fix this here?

**Comment by sdurrheimer** [comment]
I'm working on it, need to update both `promu` and `golang-builder`.
