### ISSUE TITLE
Limiting supported crossbuild targets

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/promu#66]
Expanding on https://github.com/prometheus/promu/issues/65:

It appears that package `golang.org/x/sys/unix` is failing to build for several *BSD variants:

- DragonFlyBSD (I patched this in alertmanager but haven't merged it upstream)
- OpenBSD (all `arm` builds are failing)

I'm wondering if we should focus on the main platforms that use the Prometheus ecosystem. Here's a rough list of what I think would make sense to build by default:

- Linux: All arch (although we could probably just do armv7/64, amd64, and 386)
- FreeBSD: amd64, armv7, 386
- Darwin: amd64

It seems like the *BSDs are getting less attention from the community, and I'm not sure if we want to have our builds breaking because of that.

cf. https://twitter.com/bradfitz/status/850116040319148032

Thoughts?

**Comment by RichiH** [comment]
While this can be a slippery slope, there's an argument to be made that non-mainstream OS & architectures can be treated as second class citizens.

I would propose to not disable anything on purpose, but to drop OS/arch combinations relatively quickly if no one steps up.

Carrying a text file which lists core OS/arch and points from non-supported OS/arch to issues and other rationale seems prudent to enable people who care to quickly dive in seems prudent.

**Comment by grobie** [comment]
I'm also not in favor of limiting our build targets in such a way. Let's only remove combinations which are known to not work in any project in promu, but leave the rest to project specific `.promu.yml` blacklists. We should also make it possible to remove ARMv5 only for openbsd, but not other OS like linux as discussed in #65.

**Comment by stuartnelson3** [comment]
Sounds good, closing.
