### ISSUE TITLE
Verify expected variables are set

### ISSUE THREAD

**Issue by grobie** [prometheus/promu#7]
Running promu out of the box without a complete configuration yields unexpected errors. We should tell the user what's missing and how to fix it.

```
promu build -v
Using config file: /home/grobie/code/go/src/github.com/prometheus/node_exporter/.promu.yml
 >   node_exporter
+ go build  -ldflags "-X main.Version " -o node_exporter github.com/prometheus/node_exporter
# github.com/prometheus/node_exporter
link: warning: option -X main.Version $WORK/github.com/prometheus/node_exporter.a may not work in future releases; use -X main.Version=/tmp/go-build928876611/github.com/prometheus/node_exporter.a
usage: link [options] main.o
...
```

**Comment by brian-brazil** [comment]
You need to create a failed called `VERSION` with the version in it. It's also hardcoded to call `make build`, which is not our standard build command.

**Comment by grobie** [comment]
Yeah, I figured that out. I was testing every step without having anything configured. I started a `version` package actually.

**Comment by sdurrheimer** [comment]
I see you're are testing `promu` on node_exporter. I have already done a
setup for it, take a look
https://github.com/sdurrheimer/node_exporter/commit/dc695275edea25c7a64cc4a114c40d51a7fa33e5
Le 9 avr. 2016 10:17 AM, "Tobias Schmidt" <notifications@github.com> a
écrit :

**Comment by grobie** [comment]
Thanks! I've seen it. I want to learn about promu by building each step on my own.
