### ISSUE TITLE
Include project documentation in release tarballs

### ISSUE THREAD

**Issue by grobie** [prometheus/promu#86]
More and more projects will include docs right in the repository with local links. We should have an option to include such directories in release tarballs.

**Comment by sdurrheimer** [comment]
I think [this feature](https://github.com/prometheus/promu/blob/master/doc/examples/.promu.yml#L22-L29) is already doing what you want, isn't it ?

**Comment by grobie** [comment]
Sorry. ETooEarly ENotEnoughCoffee :-)
